MODEL:
  TYPE: pvt_v2
  NAME: pvt_v2_b0_patch16_224
  PVT:
    DROP_PATH_RATE: 0.1
    PATCH_SIZE: 16
    EMBED_DIMS: [32, 64, 160, 256]
    NUM_HEADS: [1, 2, 5, 8]
    MLP_RATIOS: [8, 8, 4, 4]
    DEPTHS: [2, 2, 2, 2]
    SR_RATIOS: [8, 4, 2, 1]