MODEL:
  TYPE: pvt_v2
  NAME: pvt_v2_b2_patch16_224
  PVT:
    DROP_PATH_RATE: 0.2
    PATCH_SIZE: 16
    EMBED_DIMS: [64, 128, 320, 512]
    NUM_HEADS: [1, 2, 5, 8]
    MLP_RATIOS: [8, 8, 4, 4]
    DEPTHS: [3, 4, 6, 3]
    SR_RATIOS: [8, 4, 2, 1]