MODEL:
  TYPE: hrnet
  NAME: hrnet_w32
  NUM_CLASSES: 1000
  HRNET:
    STAGE1:
      NUM_MODULES: 1
      NUM_BRANCHES: 1
      NUM_BLOCKS: [4]
      NUM_CHANNELS: [64]
      BLOCK: 'BOTTLENECK'

    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      NUM_BLOCKS: [4, 4]
      NUM_CHANNELS: [32, 64]
      BLOCK: 'BASIC'

    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      NUM_BLOCKS: [4, 4, 4]
      NUM_CHANNELS: [32, 64, 128]
      BLOCK: 'BASIC'

    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      NUM_BLOCKS: [4, 4, 4, 4]
      NUM_CHANNELS: [32, 64, 128, 256]
      BLOCK: 'BASIC'